# SPDX-License-Identifier: GPL-2.0
#
dtb-$(CONFIG_ARCH_R9A07G044) +=  \
				myb-rzg2l-disp.dtb \
				myb-rzg2l-hdmi.dtb \
				mys-rzg2l-wifi.dtb \
				mys-rzg2l-sdcard.dtb

dtb-$(CONFIG_ARCH_R9A07G043) += myb-rzg2ul-disp.dtb \
				myt-rzg2ul-disp.dtb
